In [3]:
# Numpy

In [4]:
import numpy as np

In [6]:
x = np.array([2,5,4])
print(x)

[2 5 4]


In [7]:
type(x)

numpy.ndarray

In [10]:
l = [2,6,8,8] 
x = np.asarray(l)
type(x)

numpy.ndarray

In [11]:
print(x)

[2 6 8 8]


In [13]:
x = np.asarray(l,float)
print(x)

[2. 6. 8. 8.]


In [14]:
x.shape

(4,)

In [15]:
np.array?

In [16]:
x = np.array([[1, 2, 3], 
              [2, 3, 5]])
print(x)

[[1 2 3]
 [2 3 5]]


In [17]:
x.shape

(2, 3)

In [18]:
x[0, 0]

1

In [21]:
x[0, 0:2]

array([1, 2])

In [25]:
x[:,2]

array([3, 5])

In [26]:
x[0, :]

array([1, 2, 3])

In [31]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [33]:
x = np.eye(4,5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [35]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
x = np.random.random((3,2))
print(x)

[[0.10603383 0.72564111]
 [0.2343626  0.71635686]
 [0.55495739 0.64326578]]


In [46]:
# T = transpose
z = x.T
print(z)

[[0.04049448 0.38480634 0.21155369]
 [0.98358522 0.33063128 0.98222325]]


In [56]:
# reshape = to reshape an array to desired dimensions
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [55]:
y = x.reshape(25, 1)
print(y)

[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]


In [57]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [58]:
b = np.arange(5)

In [60]:
c = a + b
d = a - b
e = a * b
print(c, d, e)

[0 2 4 6 8] [0 0 0 0 0] [ 0  1  4  9 16]


In [63]:
print(a, a+1)

[0 1 2 3 4] [-1  0  1  2  3]


In [64]:
a = np.random.random((2, 3))
print(a)
print(a + 1)

[[0.73694125 0.90080039 0.02473713]
 [0.91198381 0.1057962  0.98958982]]
[[1.73694125 1.90080039 1.02473713]
 [1.91198381 1.1057962  1.98958982]]


In [268]:
a = np.floor(np.random.random((2,3))*10)
print(a)

[[3. 9. 2.]
 [6. 8. 9.]]


In [270]:
u = [2, 4, 6]
v = [4, 5, 2]
p1 = np.inner(v, u)
print(p1)

40


In [272]:
p2 = np.outer(u, v)
print(p2)

[[ 8 10  4]
 [16 20  8]
 [24 30 12]]


In [5]:
a = np.ones((2, 3))
b = np.ones((3, 2))
np.dot(a, b)

array([[3., 3.],
       [3., 3.]])

In [9]:
a = np.ones((2,3))
print( a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# column sum
a.sum(axis = 0)

array([2., 2., 2.])

In [18]:
# row sum 
a.sum(axis = 1)

array([3., 3.])